include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude: [lib/l10n/**/*.dart]
  # With strong mode, generated code creates errors in VS Code even if excluded.
  #strong-mode:
    #implicit-casts: false
    #implicit-dynamic: false
