include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/l10n/**/*.dart]
  # With strong mode, generated code creates errors in VS Code even if excluded.
  #strong-mode:
  #implicit-casts: false
  #implicit-dynamic: false
