name: moto_mecanico
description: A motorcycle maintenance app from Ramble \'n\' Ride.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker: ^2.0.0
  flutter_archive: ^1.0.2
  flutter_colorpicker: ^0.3.4
  http: ^0.12.2
  image_picker: ^0.6.7+7
  intl: ^0.16.1
  loading_overlay: ^0.2.1
  open_file: ^3.0.1
  package_info: ^0.4.3
  path_provider: ^1.6.14
  provider: ^4.3.2+2
  searchable_dropdown: ^1.1.3
  url_launcher: ^5.5.3
  uuid: 2.2.2
  share: '>=0.6.5+1 <2.0.0'
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/moto_mecanico.png'
  adaptive_icon_background: 'assets/launcher_icon_background.png'
  adaptive_icon_foreground: 'assets/launcher_icon_foreground.png'
 
