name: moto_mecanico
description: A motorcycle maintenance app from Ramble \'n\' Ride.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.9.1+0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  add_2_calendar: ^2.1.0
  cupertino_icons: ^1.0.0
  file_picker: ^3.0.0
  flutter_archive: ^4.0.0
  flutter_colorpicker: ^0.4.0
  http: ^0.13.0
  image_picker: ^0.8.0
  intl: ^0.17.0
  loading_overlay: ^0.3.0
  open_file: ^3.0.0
  package_info: ^2.0.0
  path_provider: ^2.0.0
  provider: ^5.0.0
  searchable_dropdown: ^1.1.0
  url_launcher: ^6.0.0
  uuid: ^3.0.0
  share: ^2.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.9.0

flutter:
  # Adds code generation (synthetic package) support 
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: 'android/fastlane/metadata/android/en-US/images/icon.png'
  adaptive_icon_background: 'assets/launcher_icon_background.png'
  adaptive_icon_foreground: 'assets/launcher_icon_foreground.png'
 
