name: moto_mecanico
description: A motorcycle maintenance app from Ramble \'n\' Ride.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.10.0+0

environment:
  sdk: ">=3.2.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  add_2_calendar: ^3.0.0
  cupertino_icons: ^1.0.0
  dropdown_search: ^5.0.0
  file_picker: ^6.1.0
  flutter_archive: ^6.0.0
  flutter_colorpicker: ^1.0.0
  http: ^1.1.0
  image_picker: ^1.0.0
  intl: ^0.18.1
  loading_overlay: ^0.3.0
  open_file: ^3.3.0
  path: ^1.8.3
  package_info_plus: ^5.0.0
  path_provider: ^2.1.0
  provider: ^5.0.0
  search_choices: ^2.2.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.0
  uuid: ^4.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0

flutter:
  # Adds code generation (synthetic package) support
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "android/fastlane/metadata/android/en-US/images/icon.png"
  adaptive_icon_background: "assets/launcher_icon_background.png"
  adaptive_icon_foreground: "assets/launcher_icon_foreground.png"
