name: CI Build

on: [push, pull_request]

jobs:
  build_appbundle:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-java@v1.4.0
      with:
        java-version: '11.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter format --set-exit-if-changed .
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
