name: Deploy on Google Play

on:
  workflow_dispatch:

jobs:
  build_appbundle:
    name: Build and deploy (Android test track)
    runs-on: ubuntu-latest
    env:
      PLAY_STORE_APP_SIGNATURE_PROPERTIES: ${{ secrets.PLAY_STORE_APP_SIGNATURE_PROPERTIES }}
      PLAY_STORE_APP_SIGNATURE: ${{ secrets.PLAY_STORE_APP_SIGNATURE }}
      PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: 'sed -i -E "s/(version: [0-9]+\.[0-9]+\.[0-9]+\+)([0-9]+)/\1$GITHUB_RUN_NUMBER/g" pubspec.yaml && grep version pubspec.yaml'
    - run: |
        echo $PLAY_STORE_APP_SIGNATURE_PROPERTIES | base64 --decode > android/key.properties
    - run: |
        echo $PLAY_STORE_APP_SIGNATURE | base64 --decode > android/app/ramblenride-play-key.jks
    - run: |
        echo $PLAY_STORE_UPLOAD_KEY | base64 --decode > android/google-service-api-key.json
    - run: flutter build appbundle
    - name: Fastlane upload
      uses:  maierj/fastlane-action@v1.4.0
      with:
        lane: playstore
        subdirectory: android
